#!/usr/bin/env python3
"""Bricksurance Data Core generator.

Compiles the platform-neutral model specs in model/ into platform artifacts:

  build/<platform>/   DDL (tables, comments, PK/FK), governance tags
                      (Databricks), reference-data seeds, data dictionary
  build/docs/         data dictionary (markdown) + ERD (mermaid)
  build/genie/        instruction text for Databricks Genie spaces

Usage:
    uv run --with pyyaml tools/generate.py

Everything under build/ is generated. Never hand-edit; change the spec and
regenerate.
"""

import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"

TYPE_MAP = {
    "databricks": {
        "string": "STRING",
        "integer": "BIGINT",
        "boolean": "BOOLEAN",
        "date": "DATE",
        "timestamp": "TIMESTAMP",
    },
    "snowflake": {
        "string": "VARCHAR",
        "integer": "NUMBER(38,0)",
        "boolean": "BOOLEAN",
        "date": "DATE",
        "timestamp": "TIMESTAMP_NTZ",
    },
}

HEADER = (
    "-- Generated by tools/generate.py from bricksurance-data-core model "
    "v{version}.\n-- Do not edit: change the spec in model/ and regenerate.\n\n"
)


def esc(text):
    """Collapse whitespace and escape single quotes for SQL string literals."""
    return " ".join(str(text).split()).replace("'", "''")


def sql_type(platform, logical):
    logical = str(logical).strip().lower()
    if logical.startswith("decimal"):
        return logical.upper()
    return TYPE_MAP[platform][logical]


def attr_type(attr):
    return attr.get("type", "string")


def load_model():
    manifest = yaml.safe_load((ROOT / "model" / "model.yaml").read_text())
    entities, code_sets, views, metric_views, functions = [], [], [], [], []
    buckets = {"entity": entities, "code_set": code_sets,
               "view": views, "metric_view": metric_views,
               "function": functions}
    for path in sorted((ROOT / "model").rglob("*.yaml")):
        if path.name == "model.yaml":
            continue
        spec = yaml.safe_load(path.read_text())
        kind = spec.get("kind")
        if kind not in buckets:
            raise ValueError(f"{path}: unknown kind {kind!r}")
        buckets[kind].append(spec)
    return manifest, entities, code_sets, views, metric_views, functions


def code_set_as_entity(cs):
    """A code set is physically a reference table; model it as an entity."""
    key = f"{cs['name']}_code"
    return {
        "kind": "entity",
        "name": cs["name"],
        "domain": "reference",
        "title": cs.get("title", cs["name"]),
        "description": cs["description"],
        "grain": f"One row per {cs.get('title', cs['name']).lower()} code.",
        "standards": cs.get("standards", {}),
        "attributes": [
            {
                "name": key,
                "type": "string",
                "required": True,
                "description": f"Code value; referenced by {key} columns across the model.",
            },
            {
                "name": "label",
                "type": "string",
                "required": True,
                "description": "Short human-readable name for the code.",
            },
            {
                "name": "description",
                "type": "string",
                "required": True,
                "description": "Business definition of the code.",
            },
        ],
        "keys": {"primary": [key]},
        "_is_code_set": True,
    }


DICTIONARY_ENTITY = {
    "kind": "entity",
    "name": "data_dictionary",
    "domain": "reference",
    "title": "Data Dictionary",
    "description": (
        "Machine-readable dictionary of every entity and attribute in the "
        "model, generated from the specs. Include this table in every data "
        "share so the semantics travel with the data."
    ),
    "grain": "One row per attribute per entity per model version.",
    "standards": {},
    "attributes": [
        {"name": "entity_name", "type": "string", "required": True,
         "description": "Entity (table) the attribute belongs to."},
        {"name": "attribute_name", "type": "string", "required": True,
         "description": "Attribute (column) name."},
        {"name": "data_type", "type": "string", "required": True,
         "description": "Logical, platform-neutral data type."},
        {"name": "is_required", "type": "boolean", "required": True,
         "description": "Whether the attribute is mandatory."},
        {"name": "definition", "type": "string", "required": True,
         "description": "Business definition of the attribute."},
        {"name": "data_classification", "type": "string", "required": False,
         "description": "Data classification: public, internal, confidential or pii."},
        {"name": "acord_ref", "type": "string", "required": False,
         "description": "ACORD vocabulary crosswalk reference."},
        {"name": "lloyds_cdr_ref", "type": "string", "required": False,
         "description": "Lloyd's Core Data Record crosswalk reference."},
        {"name": "entity_owner", "type": "string", "required": False,
         "description": "Accountable business owner of the entity, as an org role."},
        {"name": "entity_maturity", "type": "string", "required": False,
         "description": "Certification maturity of the entity: draft or certified."},
        {"name": "model_version", "type": "string", "required": True,
         "description": "Version of bricksurance-data-core this row was generated from."},
    ],
    "keys": {"primary": ["entity_name", "attribute_name", "model_version"]},
    "_is_dictionary": True,
}


# Certification attestations — the dated human act behind every 'certified'
# badge. Generated from model/governance/attestations.json so the app can back
# certification with evidence, not just a tag value.
ATTESTATION_ENTITY = {
    "kind": "entity",
    "name": "certification_attestation",
    "domain": "reference",
    "title": "Certification Attestation",
    "description": (
        "The dated attestation behind each certified model element. An element "
        "is certified only if it has a row here; the badge is evidence, not a "
        "tag. Roles, not people."
    ),
    "grain": "One row per certified element per model version.",
    "owner": "Chief Data Officer",
    "tags": {"maturity": "certified"},
    "standards": {},
    "attributes": [
        {"name": "element", "type": "string", "required": True,
         "description": "Model element (entity or metric) that is certified."},
        {"name": "element_kind", "type": "string", "required": True,
         "description": "Kind of element: entity or metric_view."},
        {"name": "certification", "type": "string", "required": True,
         "description": "Certification level attested."},
        {"name": "owner", "type": "string", "required": True,
         "description": "Accountable business owner (org role)."},
        {"name": "attested_by", "type": "string", "required": True,
         "description": "Role that made the attestation."},
        {"name": "attested_on", "type": "string", "required": True,
         "description": "Date of the attestation."},
        {"name": "evidence", "type": "string", "required": False,
         "description": "Evidence backing the certification."},
        {"name": "model_version", "type": "string", "required": True,
         "description": "Model version this attestation was recorded against."},
    ],
    "keys": {"primary": ["element", "element_kind", "model_version"]},
    "_is_attestation": True,
}


def load_attestations():
    """Load the dated attestation record (empty if the model has none yet)."""
    import json
    path = ROOT / "model" / "governance" / "attestations.json"
    if not path.exists():
        return []
    return json.loads(path.read_text()).get("attestations", [])


def attestation_seed(binding, manifest):
    table = fqn(binding, "reference", "certification_attestation")
    cols = ["element", "element_kind", "certification", "owner",
            "attested_by", "attested_on", "evidence"]
    rows = []
    for a in load_attestations():
        vals = [esc(str(a.get(c, ""))) for c in cols] + [manifest["version"]]
        rows.append("  (" + ", ".join(f"'{v}'" for v in vals) + ")")
    if not rows:
        return None
    return f"{insert_overwrite(binding['platform'], table)}\n" + ",\n".join(rows) + ";"


def schema_name(binding, domain):
    return binding["schema_pattern"].format(domain=domain)


def fqn(binding, domain, table):
    container = binding.get("catalog") or binding.get("database")
    return f"{container}.{schema_name(binding, domain)}.{table}"


def table_comment(platform, text):
    eq = " =" if platform == "snowflake" else ""
    return f"COMMENT{eq} '{esc(text)}'"


def entity_ddl(binding, manifest, entity):
    platform = binding["platform"]
    table = fqn(binding, entity["domain"], entity["name"])
    cols = []
    for a in entity["attributes"]:
        col = f"  {a['name']} {sql_type(platform, attr_type(a))}"
        if a.get("required"):
            col += " NOT NULL"
        col += f" COMMENT '{esc(a['description'])}'"
        cols.append(col)
    comment = f"{entity['description']} Grain: {entity['grain']}"
    stmts = [
        f"CREATE TABLE IF NOT EXISTS {table} (\n"
        + ",\n".join(cols)
        + f"\n)\n{table_comment(platform, comment)};"
    ]

    pk = entity["keys"]["primary"]
    stmts.append(
        f"ALTER TABLE {table} ADD CONSTRAINT pk_{entity['name']} "
        f"PRIMARY KEY ({', '.join(pk)});"
    )

    if platform == "databricks":
        # Tag keys are namespaced via the binding's tag_prefix so they never
        # collide with an organisation's governed tag policies.
        prefix = binding.get("tag_prefix", "")
        tags = {
            f"{prefix}model": manifest["model"],
            f"{prefix}model_version": manifest["version"],
            f"{prefix}domain": entity["domain"],
        }
        tags.update({f"{prefix}{k}": v for k, v in entity.get("tags", {}).items()})
        if entity.get("standards", {}).get("acord"):
            tags[f"{prefix}acord_ref"] = entity["standards"]["acord"]
        tag_sql = ", ".join(f"'{k}' = '{esc(v)}'" for k, v in tags.items())
        stmts.append(f"ALTER TABLE {table} SET TAGS ({tag_sql});")
        for a in entity["attributes"]:
            if a.get("classification"):
                stmts.append(
                    f"ALTER TABLE {table} ALTER COLUMN {a['name']} "
                    f"SET TAGS ('{prefix}classification' = '{a['classification']}');"
                )
    return "\n\n".join(stmts)


def fk_targets(entity, entity_index):
    """Yield (attr_name, ref_domain, ref_table, ref_column) for every FK-bearing
    attribute: code_set references and entity references."""
    if entity.get("_is_code_set"):
        return
    for a in entity["attributes"]:
        if a.get("code_set"):
            yield a["name"], "reference", a["code_set"], f"{a['code_set']}_code"
        elif a.get("references"):
            ref = entity_index[a["references"]]
            pk = ref["keys"]["primary"]
            if len(pk) != 1:
                raise ValueError(
                    f"{entity['name']}.{a['name']} references {ref['name']} "
                    "which has a composite primary key"
                )
            yield a["name"], ref["domain"], ref["name"], pk[0]


def entity_fk_ddl(binding, entity, entity_index):
    table = fqn(binding, entity["domain"], entity["name"])
    stmts = []
    for attr, ref_domain, ref_table, ref_col in fk_targets(entity, entity_index):
        stmts.append(
            f"ALTER TABLE {table} ADD CONSTRAINT fk_{entity['name']}_{attr} "
            f"FOREIGN KEY ({attr}) "
            f"REFERENCES {fqn(binding, ref_domain, ref_table)} ({ref_col});"
        )
    return stmts


def resolve_refs(binding, sql):
    """Replace {domain.table} placeholders in view SQL with bound FQNs."""
    import re

    return re.sub(
        r"\{(\w+)\.(\w+)\}",
        lambda m: fqn(binding, m.group(1), m.group(2)),
        sql,
    )


def view_ddl(binding, view):
    table = fqn(binding, view["domain"], view["name"])
    comment = f"{view['description']} Grain: {view['grain']}" if view.get("grain") else view["description"]
    return (
        f"CREATE OR REPLACE VIEW {table}\n"
        f"{table_comment(binding['platform'], comment)}\n"
        f"AS\n{resolve_refs(binding, view['sql']).strip()};"
    )


def metric_view_ddl(binding, mv):
    """Unity Catalog metric view (Databricks binding only)."""
    body = [f"version: {mv.get('spec_version', '0.1')}", ""]
    src_domain, src_table = mv["source"].split(".")
    body.append(f"source: {fqn(binding, src_domain, src_table)}")
    if mv.get("joins"):
        body.append("")
        body.append("joins:")
        for j in mv["joins"]:
            j_domain, j_table = j["source"].split(".")
            body.append(f"  - name: {j['name']}")
            body.append(f"    source: {fqn(binding, j_domain, j_table)}")
            # spec field is 'condition' because YAML 1.1 parses a bare 'on' key as a boolean
            body.append(f"    on: {j['condition']}")
    body.append("")
    body.append("dimensions:")
    for d in mv["dimensions"]:
        body.append(f"  - name: {d['name']}")
        body.append(f"    expr: {d['expr']}")
    body.append("")
    body.append("measures:")
    for m in mv["measures"]:
        body.append(f"  - name: {m['name']}")
        body.append(f"    expr: {m['expr']}")
    table = fqn(binding, mv["domain"], mv["name"])
    yaml_body = "\n".join(body)
    return (
        f"CREATE OR REPLACE VIEW {table}\n"
        f"COMMENT '{esc(mv['description'])}'\n"
        f"WITH METRICS\nLANGUAGE YAML\nAS $$\n{yaml_body}\n$$;"
    )


def function_ddl(binding, fn):
    """A governed tool: a UC SQL function agents may call. The ontology
    declares what agents can DO, the same way it declares what data means."""
    platform = binding["platform"]
    name = fqn(binding, fn["domain"], fn["name"])
    params = ", ".join(
        f"{p['name']} {sql_type(platform, p['type'])} COMMENT '{esc(p['description'])}'"
        for p in fn["inputs"])
    return (
        f"CREATE OR REPLACE FUNCTION {name}({params})\n"
        f"RETURNS {sql_type(platform, fn['returns']['type'])}\n"
        f"COMMENT '{esc(fn['description'])} Returns: {esc(fn['returns']['description'])}'\n"
        f"RETURN {resolve_refs(binding, fn['sql']).strip()};"
    )


def semantic_dictionary_rows(manifest, views, metric_views):
    """Dictionary rows for semantic assets, so their definitions travel too."""
    rows = []
    for mv in metric_views:
        owner = mv.get("owner", "")
        maturity = mv.get("certification", "")
        for d in mv["dimensions"]:
            rows.append((mv["name"], d["name"], "dimension", False,
                         d["description"], "", "", "", owner, maturity, manifest["version"]))
        for m in mv["measures"]:
            rows.append((mv["name"], m["name"], "measure", False,
                         m["description"], "", "", "", owner, maturity, manifest["version"]))
    return rows


def insert_overwrite(platform, table):
    into = " INTO" if platform == "snowflake" else ""
    return f"INSERT OVERWRITE{into} {table} VALUES"


def code_set_seed(binding, cs):
    table = fqn(binding, "reference", cs["name"])
    rows = ",\n".join(
        f"  ('{esc(c['code'])}', '{esc(c['label'])}', '{esc(c['description'])}')"
        for c in cs["codes"]
    )
    return f"{insert_overwrite(binding['platform'], table)}\n{rows};"


def dictionary_rows(manifest, all_entities):
    rows = []
    for e in all_entities:
        owner = e.get("owner", "")
        maturity = (e.get("tags", {}) or {}).get("maturity", "")
        for a in e["attributes"]:
            std = a.get("standards", {}) or {}
            rows.append(
                (
                    e["name"],
                    a["name"],
                    attr_type(a),
                    bool(a.get("required")),
                    a["description"],
                    a.get("classification", ""),
                    std.get("acord", ""),
                    std.get("lloyds_cdr", ""),
                    owner,
                    maturity,
                    manifest["version"],
                )
            )
    return rows


def dictionary_seed(binding, manifest, all_entities, extra_rows=()):
    table = fqn(binding, "reference", "data_dictionary")
    values = []
    for r in list(dictionary_rows(manifest, all_entities)) + list(extra_rows):
        vals = ", ".join(
            ("TRUE" if v else "FALSE") if isinstance(v, bool) else f"'{esc(v)}'"
            for v in r
        )
        values.append(f"  ({vals})")
    rows = ",\n".join(values)
    return f"{insert_overwrite(binding['platform'], table)}\n{rows};"


def generate_platform(binding, manifest, entities, code_sets, views, metric_views, functions):
    platform = binding["platform"]
    out = BUILD / platform
    out.mkdir(parents=True, exist_ok=True)
    header = HEADER.format(version=manifest["version"])

    # 00 - schemas
    stmts = []
    if binding.get("database"):
        stmts.append(f"CREATE DATABASE IF NOT EXISTS {binding['database']};")
    for d in manifest["domains"]:
        container = binding.get("catalog") or binding.get("database")
        stmts.append(
            f"CREATE SCHEMA IF NOT EXISTS {container}.{schema_name(binding, d['name'])}\n"
            f"{table_comment(platform, d['description'])};"
        )
    (out / "00_schemas.sql").write_text(header + "\n\n".join(stmts) + "\n")

    # 10 - reference: code sets + data dictionary + attestations, with seeds
    ref_entities = ([code_set_as_entity(cs) for cs in code_sets]
                    + [DICTIONARY_ENTITY, ATTESTATION_ENTITY])
    all_entities = ref_entities + entities
    parts = [entity_ddl(binding, manifest, e) for e in ref_entities]
    parts += [code_set_seed(binding, cs) for cs in code_sets]
    parts.append(dictionary_seed(binding, manifest, all_entities,
                                 semantic_dictionary_rows(manifest, views, metric_views)))
    att_seed = attestation_seed(binding, manifest)
    if att_seed:
        parts.append(att_seed)
    (out / "10_reference.sql").write_text(header + "\n\n".join(parts) + "\n")

    # 20+ - one file per business entity
    for e in entities:
        path = out / f"20_{e['domain']}_{e['name']}.sql"
        path.write_text(header + entity_ddl(binding, manifest, e) + "\n")

    # 30+ - semantic layer: plain views everywhere, metric views on Databricks
    for v in views:
        path = out / f"30_{v['domain']}_{v['name']}.sql"
        path.write_text(header + view_ddl(binding, v) + "\n")
    if platform == "databricks":
        for mv in metric_views:
            path = out / f"35_{mv['domain']}_{mv['name']}.sql"
            path.write_text(header + metric_view_ddl(binding, mv) + "\n")
        for fn in functions:
            path = out / f"40_{fn['domain']}_{fn['name']}.sql"
            path.write_text(header + function_ddl(binding, fn) + "\n")

    # 90 - all foreign keys, after every table (and its primary key) exists
    entity_index = {e["name"]: e for e in all_entities}
    fks = []
    for e in all_entities:
        fks.extend(entity_fk_ddl(binding, e, entity_index))
    (out / "90_relationships.sql").write_text(header + "\n\n".join(fks) + "\n")


def generate_docs(manifest, entities, code_sets):
    out = BUILD / "docs"
    out.mkdir(parents=True, exist_ok=True)
    ref_entities = [code_set_as_entity(cs) for cs in code_sets]
    all_entities = ref_entities + [DICTIONARY_ENTITY] + entities

    # Data dictionary (markdown)
    lines = [
        f"# {manifest['title']} — Data Dictionary",
        "",
        f"*Generated from model v{manifest['version']}. Do not edit.*",
        "",
    ]
    for e in all_entities:
        lines += [f"## {e['title']} (`{e['domain']}.{e['name']}`)", ""]
        lines += [" ".join(str(e["description"]).split()), ""]
        lines += [f"**Grain:** {' '.join(str(e['grain']).split())}", ""]
        std = e.get("standards", {}) or {}
        if std:
            refs = "; ".join(f"{k.replace('_', ' ').title()}: {v}" for k, v in std.items())
            lines += [f"**Standards:** {refs}", ""]
        lines += [
            "| Attribute | Type | Required | Definition | Classification | ACORD | Lloyd's CDR |",
            "|---|---|---|---|---|---|---|",
        ]
        for a in e["attributes"]:
            astd = a.get("standards", {}) or {}
            lines.append(
                "| {} | {} | {} | {} | {} | {} | {} |".format(
                    a["name"],
                    attr_type(a),
                    "yes" if a.get("required") else "",
                    " ".join(str(a["description"]).split()),
                    a.get("classification", ""),
                    astd.get("acord", ""),
                    astd.get("lloyds_cdr", ""),
                )
            )
        pk = ", ".join(e["keys"]["primary"])
        lines += ["", f"**Primary key:** {pk}"]
        natural = e.get("keys", {}).get("natural")
        if natural:
            lines.append(f"**Natural key:** {', '.join(natural)}")
        for q in e.get("quality", []):
            lines.append(
                f"**Quality — {q['name']}:** `{q['rule']}` — "
                + " ".join(str(q["description"]).split())
            )
        lines.append("")
    (out / "data_dictionary.md").write_text("\n".join(lines))

    # ERD (mermaid)
    erd = ["erDiagram"]
    for e in all_entities:
        erd.append(f"    {e['name']} {{")
        for a in e["attributes"]:
            mtype = attr_type(a).split("(")[0]
            flag = " PK" if a["name"] in e["keys"]["primary"] else ""
            erd.append(f"        {mtype} {a['name']}{flag}")
        erd.append("    }")
    entity_index = {e["name"]: e for e in all_entities}
    for e in entities:
        for attr, _, ref_table, _ in fk_targets(e, entity_index):
            erd.append(f"    {e['name']} }}o--|| {ref_table} : {attr}")
    (out / "erd.mmd").write_text("\n".join(erd) + "\n")


def generate_metric_catalog(manifest, metric_views):
    """A business-readable catalog of every metric: owner, certification,
    dimensions and the exact formula. This is the semantic layer as a person
    reads it - the companion to the machine-readable ontology JSON."""
    out = BUILD / "docs"
    out.mkdir(parents=True, exist_ok=True)
    lines = [f"# {manifest['title']} - Metric Catalog",
             "", f"*Generated from model v{manifest['version']}. Every measure is defined "
             "once here and physicalised as a Unity Catalog metric view; the formula is "
             "platform-neutral SQL.*", ""]
    for mv in metric_views:
        lines += [f"## {mv['title']} (`{mv['domain']}.{mv['name']}`)", ""]
        lines += [" ".join(str(mv["description"]).split()), ""]
        lines.append(f"**Owner:** {mv.get('owner', 'unassigned')} · "
                     f"**Certification:** {mv.get('certification', 'draft')} · "
                     f"**Source:** `{mv['source']}`")
        lines += ["", "**Dimensions:** " + ", ".join(d["name"] for d in mv["dimensions"]), ""]
        lines += ["| Measure | Definition | Formula |", "|---|---|---|"]
        for m in mv["measures"]:
            formula = " ".join(str(m["expr"]).split()).replace("|", "\\|")
            lines.append(f"| `{m['name']}` | {' '.join(str(m['description']).split())} "
                         f"| `{formula}` |")
        lines.append("")
    (out / "metric_catalog.md").write_text("\n".join(lines))


def generate_genie(binding, manifest, entities, code_sets, views=(), metric_views=()):
    out = BUILD / "genie"
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Genie instructions — {manifest['title']} v{manifest['version']}",
        "",
        "You answer questions about the insurance business of Bricksurance SE "
        "using the canonical data model below. Definitions come from the "
        "model's data dictionary; prefer them over guesses. When presenting "
        "results, always resolve identifier columns (anything ending _id) to "
        "business names or labels by joining the referenced table - e.g. "
        "party_id -> party.name - and never show raw surrogate ids unless "
        "the user asks for them.",
        "",
        "## Tables",
        "",
    ]
    ref_entities = [code_set_as_entity(cs) for cs in code_sets]
    for e in ref_entities + [DICTIONARY_ENTITY] + entities:
        table = fqn(binding, e["domain"], e["name"])
        lines.append(f"- `{table}` — {' '.join(str(e['description']).split())} "
                     f"Grain: {' '.join(str(e['grain']).split())}")
    # Joins are declared as PRIMARY KEY / FOREIGN KEY constraints in Unity
    # Catalog, so Genie infers them from the catalog - no need to list every
    # FK here (and doing so overflows the 65k instruction limit at this scale).
    lines += ["", "Foreign-key relationships are declared on the tables; use "
              "them for joins. Resolve any *_id column to a business name by "
              "joining its referenced table.", ""]
    if metric_views:
        lines += ["", "## Metrics", ""]
        lines.append(
            "For KPI questions (premium, incurred, loss ratio and similar), "
            "PREFER the metric views below over hand-written aggregations. "
            "Query measures with MEASURE(<name>) and GROUP BY dimensions. "
            "Amounts are in original currency: always group by or filter on "
            "currency_code before summing money.")
        lines.append("")
        for mv in metric_views:
            lines.append(f"- `{fqn(binding, mv['domain'], mv['name'])}` — "
                         f"{' '.join(str(mv['description']).split())}")
            for d in mv["dimensions"]:
                lines.append(f"  - dimension {d['name']}: {' '.join(str(d['description']).split())}")
            for m in mv["measures"]:
                lines.append(f"  - MEASURE({m['name']}): {' '.join(str(m['description']).split())}")
    lines += ["", "## Vocabulary", ""]
    for cs in code_sets:
        codes = ", ".join(f"{c['code']} ({c['label']})" for c in cs["codes"])
        lines.append(f"- {cs['title']}: {codes}.")
    (out / "genie_instructions.md").write_text("\n".join(lines) + "\n")


def generate_ontology(manifest, entities, code_sets, views, metric_views, functions):
    """The whole model as ONE portable JSON document — the ontology.

    Platform-neutral (no bindings), deterministic, versioned. This is the
    exchange artifact: an adopter imports it with tools/import_ontology.py and
    owns the same model. Relationships are included (derived) for consumers
    that don't want to re-derive them from attributes.
    """
    import json

    entity_index = {e["name"]: e for e in entities}
    relationships = []
    for e in entities:
        for attr, ref_domain, ref_table, ref_col in fk_targets(e, entity_index):
            relationships.append({
                "from_entity": e["name"],
                "attribute": attr,
                "to": ref_table,
                "to_kind": "code_set" if ref_domain == "reference" and attr.endswith("_code") else "entity",
                "to_attribute": ref_col,
            })

    doc = {
        "ontology_format": "bricksurance-data-core/ontology-v1",
        "name": manifest["model"],
        "title": manifest["title"],
        "version": manifest["version"],
        "description": " ".join(str(manifest["description"]).split()),
        "standards_basis": (
            "Aligned to ACORD terminology with an indicative Lloyd's Core Data "
            "Record crosswalk. The crosswalk is a hand-authored, best-knowledge "
            "mapping to ACORD / Lloyd's CDR element names, not a verified extract "
            "from the licensed models; element names are cited only, and the "
            "licensed standards are not reproduced."
        ),
        "domains": manifest["domains"],
        "code_sets": code_sets,
        "entities": entities,
        "views": views,
        "metric_views": metric_views,
        "functions": functions,
        "relationships": relationships,
        "attestations": load_attestations(),
    }
    out = BUILD / "ontology"
    out.mkdir(parents=True, exist_ok=True)
    (out / f"{manifest['model']}.ontology.json").write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + "\n")

    # a self-describing README so the JSON is usable by anyone, standalone
    counts = (f"{len(entities)} entities, {len(code_sets)} code sets, "
              f"{len(views)} views, {len(metric_views)} metric views, "
              f"{len(functions)} functions, {len(relationships)} relationships")
    (out / "README.md").write_text(f"""# {manifest['title']} — Ontology Export

`{manifest['model']}.ontology.json` is the **entire semantic model in one
platform-neutral file** (format `bricksurance-data-core/ontology-v1`,
v{manifest['version']}): {counts}.

## What is in it

| Key | What it holds |
|---|---|
| `domains` | The {len(manifest['domains'])} business domains |
| `entities` | Tables: attributes with type, definition, data classification, keys, quality rules, ACORD/Lloyd's crosswalk |
| `code_sets` | Controlled vocabularies **with their allowed values** |
| `views` / `metric_views` | Semantic views and metrics — **each measure carries its exact SQL formula, plus owner and certification** |
| `functions` | Governed callable tools (name, typed inputs, return, body) |
| `relationships` | The full foreign-key graph, pre-derived |

Every attribute and measure has a business definition. This is a complete,
self-contained specification: a reader needs nothing else to understand or
re-implement the model.

## Two ways to use it

1. **Think about your own implementation** — read the JSON (or the companion
   `data_dictionary.md` and `metric_catalog.md`). It is deliberately
   platform-agnostic: entities, definitions, relationships and metric formulas,
   with no vendor specifics. Map it onto whatever platform you run.
2. **Stand it up on Databricks** — follow `INSTALL_DATABRICKS.md`. In short:
   drop this JSON into a fork, add a one-file binding (your catalog + schema
   naming), run the generator, deploy. ~30 minutes to a governed Unity Catalog
   with definitions, keys, tags, metric views and Genie context.

## Round-trip guarantee

`tools/import_ontology.py --input <this file> --target <dir>` regenerates the
full spec tree; export→import→export is verified byte-identical. Adopting the
model, or exchanging it between organisations, is this one file.
""")
    # make the export folder a self-contained hand-off bundle
    import shutil
    for src in (BUILD / "docs" / "data_dictionary.md",
                BUILD / "docs" / "metric_catalog.md",
                ROOT / "docs" / "INSTALL_DATABRICKS.md"):
        if src.exists():
            shutil.copy(src, out / src.name)


def main():
    manifest, entities, code_sets, views, metric_views, functions = load_model()
    if BUILD.exists():
        shutil.rmtree(BUILD)
    generated = []
    for binding_path in sorted((ROOT / "bindings").glob("*.yaml")):
        binding = yaml.safe_load(binding_path.read_text())
        generate_platform(binding, manifest, entities, code_sets, views, metric_views, functions)
        generated.append(binding["platform"])
        if binding["platform"] == "databricks":
            generate_genie(binding, manifest, entities, code_sets, views, metric_views)
    generate_docs(manifest, entities, code_sets)
    generate_metric_catalog(manifest, metric_views)
    generate_ontology(manifest, entities, code_sets, views, metric_views, functions)
    n_files = sum(1 for _ in BUILD.rglob("*") if _.is_file())
    print(
        f"Generated {n_files} files for platforms {', '.join(generated)} "
        f"from {len(entities)} entities, {len(code_sets)} code sets, "
        f"{len(views)} views, {len(metric_views)} metric views and {len(functions)} functions "
        f"(model v{manifest['version']})."
    )


if __name__ == "__main__":
    main()
